### ISSUE TITLE
all public functions should probably be OsStr(ing) based

### ISSUE THREAD

**Issue by xaverdh** [kpcyrd/kmod-rs#24]
Just switching them would break the api, not sure how to go about this..

**Comment by xaverdh** [comment]
I can think of two solutions:
* extend the type of the inputs to something that allows passing both `&str` as well as `&OsStr`
* expose a new namespace with just the `OsStr` types

**Comment by xaverdh** [comment]
Ah, they actually are now. Just not in the latest release..

**Comment by kpcyrd** [comment]
It's now part of 0.5.0. Cheers!
